config/routes.rb
Rails.application.routes.draw do
  resources :stock_subjects, only: [:index, :create, :new, :destroy, :show] do
    collection do
      delete :clear
    end
  end

  root 'faculties#index'
  
  get 'usage' => 'static_pages#usage'
  get 'agreement' => 'static_pages#agreement'
  get 'notice' => 'static_pages#notice'
  get 'q_and_a' => 'static_pages#q_and_a'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#post_contact'
  get 'popularity' => 'static_pages#popularity'
  
  resources :faculties, only: [:index, :show] do
    collection do
      get :list
    end
  end
  
  resources :summarized_subjects, only: [:show]
end

app/controllers/static_pages_controller.rb
require 'slack/incoming/webhooks'

class StaticPagesController < ApplicationController
  def usage
  end
  
  def agreement
  end
  
  def notice
  end
  
  def q_and_a
  end
  
  def contact
    @uuid = cookies.signed["uuid"]
  end
  
  def post_contact
    uuid = params[:uuid]
    email = params[:email]
    content = params[:content]
    if content.present?
      slack = Slack::Incoming::Webhooks.new ENV['SLACK_URL']
      attachments = [{
        title: "問い合わせ UUID:#{uuid}, mail:#{email}",
        text: "#{content}",
        color: "#fbec00"
      }]
      slack.post "@johshisha From #{email}", attachments: attachments
      redirect_to contact_url, :notice => "問い合わせありがとうございました．今後ともよろしくお願いします．"
    else
      redirect_to contact_url, :alert => "内容が記入されていません．"
    end
  end
  
  def popularity
    limit_num = 20
    @faculties = Faculty.all
    if faculty_id = params["faculty_id"]
      ordered = StockedLog.joins(:summarized_subject).where("faculty_id = #{faculty_id}").group(:subject_id).order('count_subject_id desc').count('subject_id')
    else
      ordered = StockedLog.group(:subject_id).order('count_subject_id desc').count('subject_id')
    end
    keys = ordered.keys
    @values = ordered.values
    @subjects = SummarizedSubject.where(subject_id: keys).sort_by {|p| keys.index(p.subject_id) }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/agreement.html.erb
<h1>当サイトご利用にあたって</h1>

<p>
  SyllabusPlusをご利用いただきありがとうございます．<br>
  当サイトをご利用の際には，以下の利用規約が適用されますので，ご利用の際には必ずお読みください．
</p>
<hr>
<h3>本利用規約について</h3>
<ul>
  <li>本利用規約は当サイトの利用条件を定めるものです．当サイトをご利用される際には，本規約に同意したものとみなされます．</li>
  <li>当サイトでは，相当の事由があると判断した場合には，利用者の事前の承諾を得ることなく本利用規約をいつでも変更することができるものとします．</li>
  <li>変更後の本利用規約は，当サイトに表示した時点より効力を生じるものとし，また，効力が生じた後，当サイトを利用される場合には変更後の本利用規約に同意したものとみなされます．</li>
</ul>

<h3>当サイトのサービス提供の中断，変更等</h3>
<ul>
  <li>管理者が必要と判断した場合には，事前に通知することなく当サイトの内容の変更，または提供の停止・中止することができるものとします．</li>
</ul>

<h3>免責事項</h3>
<ul>
  <li>利用者は利用者自身の自己責任において当サイトを利用するものとし，当サイトを利用してなされた一切の行為およびその結果についてその責任を負うものとします．</li>
  <li>当サイトは当サイトの利用により発生した利用者の損害については，一切の賠償責任を負いません．</li>
</ul>

<br><br>
2017年3月15日：施行
<br><br>

app/views/static_pages/contact.html.erb
<h1>ご意見・ご要望などをお聞かせください</h1>
<div class="message">
  <p>
    この機能が使いづらい等，遠慮なく教えていただけますとうれしいです！<br>
    今後の機能改善に繋がりますのでよろしくお願いします．<br>
    (ご要望にお答えできない場合もございますので，お了承ください．)<br>
    また，わからない点がございましたらお気軽にご質問ください．よくある質問は<%= link_to "こちら", q_and_a_path, target: :_blank %>
  </p>
</div>
<div class="modal-dialog">
  <%= form_tag contact_path, class: "contact-form" do %>
    <%= hidden_field_tag(:uuid, @uuid) %>
    <p>
      E-mail (返事が必要な方はご記入ください)
    </p>
    <p>
      <%= email_field_tag :email, '', :size => "40" %>
    </p>
    <p>
      内容
    </p>
    <p>
      <%= text_area_tag :content, '', :size => "40x7" %>
    </p>
    <p>
      <%= submit_tag "送信する", class: "btn" %>
    </p>
  <% end %>
</div>

app/views/static_pages/notice.html.erb
<h1>ご利用にあたっての注意事項</h1>
<p>
  SyllabusPlusをご利用いただきありがとうございます．<br>
  当サイトをご利用の際には以下の注意事項をよく読んだ上でご利用ください．<br>
  また，合わせて<%= link_to "利用規約", agreement_path %>もお読みください．
</p>
<hr>
<h3>当サイトは大学公式のサイトではございません</h3>
<p>
  当サイトは大学の情報を参考に，個人で運営されているサイトです．<br>
  公式のサイトではございませんので，ご注意ください．
</p>

<h3>自己責任でご利用ください</h3>
<p>
  当サイトに記載されている情報は誤りを含む場合がございます．<br>
  当サイトを利用される際には，<strong>情報に誤りがないかしっかりと確認した上</strong>で，<strong>自己責任で</strong>ご利用ください．
</p>

<h3>学校のPCでご利用の際にはデータは削除されます</h3>
<p>
  当サイトでは科目のストック情報等はブラウザに保存しています．<br>
  <strong>学校のPCではシャットダウン時にすべて削除されてしまいます</strong>ので，情報を残しておきたい場合にはメモを取るなどご自身で管理いただきますようお願いします．
</p>

<h3>ブラウザに保存する情報について</h3>
<p>
  当サイトでは，Cookieを利用してブラウザに情報を保存しております．<br>
  保存する情報は，ユーザ識別子・選択済み学部情報・ストック科目・時間割が含まれます．<br>
  個人情報等は含まないものの，他人のPCで利用しない等，扱いにはご注意ください．<br>
</p>

<h3>広告について</h3>
<p>
  当サイトでは一部広告を表示させていただいております．<br>
  これは当サイトを保守・運用していくために必要なものですのでご理解いただけますと幸いです．
</p>

<h3>ご意見・ご要望など</h3>
<p>
  ご意見・ご要望などございましたら，お手数ですが<%= link_to "こちら", contact_path %>よりお願いします．<br>
  こういった機能を追加して欲しい，ここの動作がおかしい等どんどんお待ちしております．<br>
  ただし，出来る限り対応させていただきますが，必ずしも対応できるとは限りませんのでご理解ください．
</p>

app/views/static_pages/popularity.html.erb
<h1>人気科目</h1>
<h3>Stockされた回数の多い科目<%= (faculty_id = params['faculty_id']) ? " (#{@faculties.find(faculty_id).name})" : "" %></h3>

<style type="text/css">
td, th {
padding: 10px 20px;
}
</style>

<%= form_tag(popularity_path, method: "get") do %>
  絞り込み検索：<%= select_tag "faculty_id", options_from_collection_for_select(@faculties, "id", "name") %>
  <%= submit_tag("検索") %>
<% end %>
<p><%= button_to "リセット", popularity_path, method: "get" %><p>


<table>
  <thead>
    <tr>
      <th width='30%'>科目</th>
      <th width='10%'>id</th>
      <th width='10%'>平均評点</th>
      <th width='20%'>学部</th>
      <th width='10%'>回数</th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each_with_index do |subject, i| %>
      <tr>
        <td><%= link_to subject.name, subject, target: :_blank %></td>
        <td><%= subject.subject_id %></td>
        <td><%= subject.mean_score %></td>
        <td><%= (name = @faculties.find(subject.faculty_id).name).include?('（') ? name.match(/（(.+)）/)[1] : name %></td>
        <td><%= @values[i] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/static_pages/q_and_a.html.erb
<h1>よくある質問</h1>
<ol>
  <li class="question">
    <div>
      <h3>表示されている成績評価基準と元データはどう違うか</h3>
      <p>
        表示されているデータはある科目のこれまでの数年分のデータをふまえた統計結果です．
        最新のデータだけを使っているわけではなく，昔のデータも踏まえた上で平均点を算出しています．
        最新の詳細な数値を知りたい方はお手数ですが，大学のサイトにてご確認ください．
      </p>
    </div>
  </li>
  <li class="question">
    <div>
      <h3>表示されている内容がシラバスと違う</h3>
      <p>
        このサイトで使用しているデータは自動で収集したもので，一部間違いを含む場合もあります．
        ご利用の際にはその点を十分理解した上でご利用ください．
        また，間違いを見つけた場合にはお手数ですが，<%= link_to "こちら", contact_path %>よりご一報いただければ幸いです．
      </p>
    </div>
  </li>
  <li class="question">
    <div>
      <h3>目当ての科目が検索結果に表示されない</h3>
      <p>
        ローマ数字(I, Vなど)はアルファベットのI(i)，V(v)で検索してください．
        空白区切りでの検索はできませんので，注意してください．
        それでも見つからない場合はデータが無い場合があります．大学のサイトで検索してみてください．
      </p>
    </div>
  </li>
  <li class="question">
    <div>
      <h3>この機能が使いにくい・この機能がほしい</h3>
      <p>
        貴重な意見ですので，ぜひ<%= link_to "こちら", contact_path %>にて教えてください！
        出来る限り迅速に対応させていただこうと思います！（対応できないものもあります）
      </p>
    </div>
  </li>
</ol>

<br>

app/views/static_pages/stocked.html.erb
<table class="subject_table">
  <tr>
    <th class="subject_name">科目名</th>
    <th>科目コード</th>
    <th class="score">A</th>
    <th class="score">B</th>
    <th class="score">C</th>
    <th class="score">D</th>
    <th class="score">F</th>
    <th class="score">平均評点</th>
  </tr>
  <%= render @subjects %>
</table>

app/views/static_pages/usage.html.erb
<h1>使い方</h1>
<div class="usage">
  <div class="notice">
    <p>※本サイトはPC向けに作成したものです</p>
  </div>
  <p><%= link_to "ご利用にあたっての注意事項", notice_path, target: :_blank %>をお読みの上ご利用ください．</p>
  <h3>科目検索機能</h3>
  <hr>
  <p>ホーム画面より，検索したい科目がある学部を選択してください．</p>
  <p>複数学部選択可能です．</p>
  <p>選択し終えたら”学部一覧を閉じる”のボタンを押せば隠れるので邪魔になりません．（再度押せば開きます）</p>
  <%= image_tag("usage/select_faculty.png", alt: "学部を選択する", width: "250px",  class: "usage_image") %>
  <p>学部に対応する科目の一覧が表示されます．</p>
  <%= image_tag("usage/all_subjects.png", alt: "科目の一覧", width: "60%", class: "usage_image") %>
  <p>一覧ページでできることは以下．</p>
  <ul class="usage-ul">
    <li>項目のソート：降順，昇順に並び替えることができます．</li>
    <li>表示件数の変更：10, 25, 50, 100から選択できます．</li>
    <li>検索：科目名，先生の名前(複数人の場合は最初の人)で検索できます．</li>
    <li>シラバスへのリンク：科目名をクリックしてシラバスへ飛ぶことができます．</li>
    <li>学期検索：学期ごとに絞り込むことができます．</li>
  </ul>

  <h3>ストック機能</h3>
  <hr>
  <div class="notice">
    <p>ストック機能はブラウザにデータを保存しています．</p>
    <p>ブラウザを変えたり，cookieをクリアしてしまうとデータは消去されてしまいます．</p>
    <p>また学校のPCではシャットダウンすると自動的に消去されます．</p>
  </div>
  <p>受講したい，検討したい科目があれば"stock"ボタンをクリックすると，ストックしておくことができます．</p>
  <%= image_tag("usage/stock_button.png", alt: "stockボタン", width: "30%", class: "usage_image") %>
  
  <p>講義の曜日，時間を入力すると自動的に時間割表にまとめてくれます．</p>

  <p>ストックした科目は，一番上にある<strong><%= link_to "保存した科目を見る", stock_subjects_path %></strong>を押すと見ることができます．</p>
  <p>ここでは，ストックした科目の時間割表示，一覧表示を確認することができます．</p>
  <%= image_tag("usage/time_schedule.png", alt: "時間割", width: "60%", class: "usage_image") %>


  <h3>使い方がわからない，動作がおかしい，などあれば<%= link_to "こちら", contact_path, target: :_blank %>でお伝え下さい．</h3>
  <br>

</div>