config/routes.rb
Rails.application.routes.draw do
  resources :stock_subjects, only: [:index, :create, :new, :destroy, :show] do
    collection do
      delete :clear
    end
  end

  root 'faculties#index'
  
  get 'usage' => 'static_pages#usage'
  get 'agreement' => 'static_pages#agreement'
  get 'notice' => 'static_pages#notice'
  get 'q_and_a' => 'static_pages#q_and_a'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#post_contact'
  get 'popularity' => 'static_pages#popularity'
  
  resources :faculties, only: [:index, :show] do
    collection do
      get :list
    end
  end
  
  resources :summarized_subjects, only: [:show]
end

app/controllers/stock_subjects_controller.rb
class StockSubjectsController < ApplicationController
  def index
    weeks, periods = get_week_and_periods
    @weeks = weeks
    @periods = periods
    @schedules = schedules "get"
    subject_ids = ids "get"
    @subjects = SummarizedSubject.where(subject_id: subject_ids)
    # 長さが違う場合は何らかのバグなので，めんどくさいからリセットする
    if @schedules.length != @subjects.length
      cookies.delete "subject_schedules"
      cookies.delete "subjects"
      @schedules = {}
      @subjects = SummarizedSubject.none
    end
  end
  
  def show
    weeks, periods = get_week_and_periods
    @weeks = weeks
    @periods = periods
    @subject = SummarizedSubject.find_by(subject_id: params[:id])
    @present = ids("get").include?(@subject.subject_id.to_s)
  end

  def new
    weeks, periods = get_week_and_periods
    @weeks = weeks
    @periods = periods
  end

  def create
    weeks, periods = get_week_and_periods
    week = params[:week]
    period_array = params[:periods]
    subject_id = params[:subject_id]
    respond_to do |format|
      if week && period_array && subject_id
        schedules "add", [subject_id, [week, period_array]]
        ids "add", subject_id
        uuid = cookies.signed["uuid"]
        begin
          if log = StockedLog.find_by(uuid: uuid, subject_id: subject_id)
            log.update!(uuid: uuid, subject_id: subject_id, week: week, periods: period_array, deleted: false)
          else
            StockedLog.create!(uuid: uuid, subject_id: subject_id, week: week, periods: period_array)
          end
        rescue
          # Herokuで保存失敗したときの通知
          slack = Slack::Incoming::Webhooks.new ENV['SLACK_URL']
          attachments = [{
            title: "保存失敗 UUID:#{uuid}",
            text: "uuid: #{uuid}, subject_id: #{subject_id}, week: #{week}, periods: #{period_array}",
            color: "#F35A00"
          }]
          slack.post "@johshisha", attachments: attachments
        end
        format.js { @status = {"status": "success", "id": subject_id} }
      else
        format.js { @status = {"status": "fail"} }
      end
    end
  end

  def destroy
    subject_id = params[:id]
    respond_to do |format|
      if subject_id
        schedules "delete", subject_id
        ids "delete", subject_id
        uuid = cookies.signed["uuid"]
        if log = StockedLog.find_by(uuid: uuid, subject_id: subject_id)
          log.update_attribute(:deleted, true)
        end
        format.js { @status = {"status": "success", "id": subject_id} }
      else
        format.js { @status = {"status": "fail"} }
      end
    end
  end
  
  def clear
    uuid = cookies.signed["uuid"]
    StockedLog.where(subject_id: ids("get")).update_all(deleted: true)
    cookies.delete "subject_schedules"
    cookies.delete "subjects"
    redirect_to stock_subjects_url
  end
  
  def get_week_and_periods
    return [["月", "火", "水", "木", "金", "土"], Array(1..7)]
  end
  
  def schedules(method, data=nil)
    cookie_hash = cookies["subject_schedules"].present? ? JSON.parse(cookies["subject_schedules"]).stringify_keys : {}
    if method == 'add'
      subject_id, value = data[0], data[1]
      cookie_hash.store(subject_id, value)
    elsif method == 'delete'
      cookie_hash.delete(data)
    elsif method == 'get'
      return cookie_hash
    end
    cookies.permanent["subject_schedules"] = JSON.dump cookie_hash.stringify_keys
  end
  
  def ids(method, data=nil)
    subject_ids = (cookies["subjects"] || "").split("&").reject(&:blank?)
    if method == "add"
      subject_ids.push(data)
    elsif method == 'delete'
      subject_ids.delete(data)
    elsif method == 'get'
      return subject_ids
    end
    cookies.permanent["subjects"] = subject_ids
  end
end

app/helpers/stock_subjects_helper.rb
module StockSubjectsHelper
end

app/views/stock_subjects/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <p><%= @subject.name %></p>
    <p><%= "#{int2term @subject.term}学期" %></p>
    <div class='modal-error-field'></div>
    <% if @present %>
      <%= form_tag "/stock_subjects/#{@subject.subject_id}", method: "delete", remote: true, class: "modal-form" do %>
        <p>ストックから削除しますか？</p>
        <%= submit_tag "削除", class: "btn" %>
      <% end %>
    <% else %>
      <%= form_tag stock_subjects_path, remote: true, class: "modal-form" do %>
        <%= hidden_field_tag(:subject_id, @subject.subject_id) %>
        <table class="modal-table">
          <tr>
            <th><%= label_tag(:week, "曜日") %></th>
            <th><%= label_tag(:period, "時間") %></th>
          </tr>
          <tr>
            <td width="100">
              <% @weeks.each_with_index do |week, i| %>
                <p>
                  <label>
                    <%= week %> : <%= radio_button_tag "week", i %>
                  </label>
                </p>
              <% end %>
            </td>
            <td width="100">  
              <% @periods.each_with_index do |period, i| %>
                <p>
                  <label>
                    <%= period %> : <%= check_box_tag "periods[]", i %>
                  </label>
                </p>
              <% end %>
            </td>
          </tr>
        </table>
        <%= submit_tag "ストックする", class: "btn" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/stock_subjects/_schedules.html.erb
<% term_name = ["spring", "autumn"] %>
<h2><% term == 0 ? 春学期 : 秋学期 %></h2>
<table class="tmo_ctt <%= term_name[term] %>-term" id="<%= term %>">
  <thead>
    <tr>
      <th class="blank"></th>
      <% weeks.each do |week| %>
        <th class="week"><%= week %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% periods.each_with_index do |period, p_i| %>
      <tr>
        <th class="time"><%= period %></th>
        <% weeks.each_with_index do |week, w_i| %>
          <td week="<%= w_i %>" period="<%= p_i %>" class="schedule-data-td" id="schedule-<%= w_i %>_<%= p_i %>">
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stock_subjects/_term-info.html.erb
<% term_name = ["spring", "autumn"] %>
<div class="schedule">
  <h2><%= term == 0 ? "春学期" : "秋学期" %></h2>
  <table class="tmo_ctt <%= term_name[term] %>-term" id="<%= term %>">
    <thead>
      <tr>
        <th class="blank"></th>
        <% weeks.each do |week| %>
          <th class="week"><%= week %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% periods.each_with_index do |period, p_i| %>
        <tr>
          <th class="time"><%= period %></th>
          <% weeks.each_with_index do |week, w_i| %>
            <td week="<%= w_i %>" period="<%= p_i %>" class="schedule-data-td" id="schedule-<%= w_i %>_<%= p_i %>">
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="stocked <%= term_name[term] %>-term">
  <table class="stocked_table">
    <tr>
      <th class="subject_name">科目名</th>
      <th class="teacher_name">先生</th>
      <th class="score">A</th>
      <th class="score">B</th>
      <th class="score">C</th>
      <th class="score">D</th>
      <th class="score">F</th>
      <th class="mean-score">平均評点</th>
      <th class="credit">単位</th>
      <th>削除</th>
    </tr>
    <% subjects.each do |summarized_subject| %>
      <tr class="table-data-<%= summarized_subject.subject_id %>">
        <td class="subject_name-data"><%= link_to summarized_subject.name, summarized_subject.url %></td>
        <td class="teacher_name"><%= summarized_subject.teacher_name %></td>
        <td class="score"><%= summarized_subject.A.round(1) %></td>
        <td class="score"><%= summarized_subject.B.round(1) %></td>
        <td class="score"><%= summarized_subject.C.round(1) %></td>
        <td class="score"><%= summarized_subject.D.round(1) %></td>
        <td class="score"><%= summarized_subject.F.round(1) %></td>
        <td class="score"><%= summarized_subject.mean_score.round(1) %></td>
        <td class="credit"><%= summarized_subject.credit %></td>
        <td class="delete-stock">
          <%= form_tag "/stock_subjects/#{summarized_subject.subject_id}", method: "delete", remote: true do %>
            <%= submit_tag "削除", class: "btn delete-stock-button" %>
          <% end %>
        </td>
        <td class="credit-td"><%= summarized_subject.credit %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="<%= term_name[term] %>-credit">
  <p>単位小計：<span class="<%= term_name[term] %>-credit-value"></span>単位</p>
</div>

app/views/stock_subjects/create.js.erb
<% if @status[:status] == 'success' %>
$("#stock-modal").modal("hide");
$('<%= ".stock-button-#{@status[:id]}" %>').text("unstock");
<%  elsif @status[:status] == 'fail' %>
$('.modal-error-field').text('入力が間違っています');
<% end %>

app/views/stock_subjects/destroy.js.erb
<% if @status[:status] == 'success'%>
var url = window.location.href;
if (url == "<%= stock_subjects_url %>"){
  $('<%= ".table-data-#{@status[:id]}" %>').remove();
  $('<%= ".schedule-data-#{@status[:id]}" %>').remove();
  update_credit();
}else{
  $("#stock-modal").modal("hide");
  $('<%= ".stock-button-#{@status[:id]}" %>').text("stock");
}
<%  elsif @status[:status] == 'fail' %>
alert('error!');
<% end %>

app/views/stock_subjects/index.html.erb
<% spring_subjects = @subjects.where(term: 0) %>
<% autumn_subjects = @subjects.where(term: 1) %>

<%= render partial: 'term-info', locals: {weeks: @weeks, periods: @periods, term: 0, subjects: spring_subjects} %>
<%= render partial: 'term-info', locals: {weeks: @weeks, periods: @periods, term: 1, subjects: autumn_subjects} %>


<div class="sum-credit">
  <h4>単位合計：<span class="sum-credit-value"></span>単位<small>（必ずご自分でご確認ください）</small></h4>
</div>
<div class="delete-all-stock">
  <%= link_to 'すべて削除する', clear_stock_subjects_path, method: :delete, class: "btn btn-default", data: { confirm: '本当によろしいですか？'} %>
</div>


<script>
<!-- 時間割に科目を追加する  -->
<!--
  <% @schedules.each do |k,v| %>
    <% id, week, periods = k, v[0], v[1] %>
    <% subject = @subjects.find_by(subject_id: id) %>
    <% periods.each do |period| %>
      var class_id = "schedule-data-<%= id %>";
      var subject_name = '●<%= subject.name %>';
      schedule_table_add(class_id, subject_name, <%= week %>, <%= period %>, <%= subject.term %>);
    <% end %>
  <% end %>

  function update_credit(){
    function calc_term_credit(term){
      sum = 0;
      $("."+term+"-term").find('.credit-td').each(function() {
        sum += Number($(this).text());
      });
      $("."+term+"-credit-value").text(sum);
    }
    calc_term_credit("spring");
    calc_term_credit("autumn");
    $(".sum-credit-value").text(Number($(".spring-credit-value").text()) + Number($(".autumn-credit-value").text()));
  }
  update_credit();
// -->
</script>

app/views/stock_subjects/new.js.erb
$("#stock-modal").html("<%= escape_javascript(render 'form') %>")
$("#stock-modal").modal("show")

app/views/stock_subjects/show.js.erb
$("#stock-modal").html("<%= escape_javascript(render 'form') %>")
$("#stock-modal").modal("show")