config/routes.rb
Rails.application.routes.draw do
  resources :stock_subjects, only: [:index, :create, :new, :destroy, :show] do
    collection do
      delete :clear
    end
  end

  root 'faculties#index'
  
  get 'usage' => 'static_pages#usage'
  get 'agreement' => 'static_pages#agreement'
  get 'notice' => 'static_pages#notice'
  get 'q_and_a' => 'static_pages#q_and_a'
  get 'contact' => 'static_pages#contact'
  post 'contact' => 'static_pages#post_contact'
  get 'popularity' => 'static_pages#popularity'
  
  resources :faculties, only: [:index, :show] do
    collection do
      get :list
    end
  end
  
  resources :summarized_subjects, only: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="同志社大学の学生のための履修支援サービス．科目を検索しやすく，成績分布（A率，F率）の解析結果を一覧で見ることができる．
          シラバスへ簡単に飛ぶことができ，その場で時間割も作成できる．同志社大学の学生が履修を組む際に便利なサービスです．楽単（楽な単位）も検索できますが，そういう用途ではありません．">
    <title><%= content_for?(:title) ? yield(:title) : "SyllabusPlus" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-93161115-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body>
    <div id="sticker">
    <div class="navbar navbar-default">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">SyllabusPlus</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "使い方", usage_path  %></li>
            <li><%= link_to "保存した科目を見る", stock_subjects_path %></li>
            <li><%= link_to "問い合わせ", contact_path  %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <div clas="links">
              <ul class="nav nav-list">
                <li class="nav-header">リンク</li>
                <li>
                  <%= link_to "公式Twitter", "https://twitter.com/SyllabusPlus", target: :_blank %>
                  <small class="description">新機能リリースなどはこちらで通知しています．</small>
                </li>
                <li>
                  <%= link_to "注意事項", notice_path, target: :_blank %>
                  <small class="description">ご利用の際には必ずお読みください．</small>
                </li>
                <li>
                  <%= link_to "問い合わせ", contact_path, target: :_blank %>
                  <small class="description">質問・要望などはこちらから．</small>
                </li>
                <!-- <li><%= link_to "Link2", "/path2"  %></li> -->
                <!-- <li><%= link_to "Link3", "/path3"  %></li> -->
              </ul>
            </div>
            <br>
            <div class="adsense1">
              <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
              <!-- syllabus_plus_small -->
              <ins class="adsbygoogle"
                   style="display:inline-block;width:200px;height:200px"
                   data-ad-client="ca-pub-8372481220104140"
                   data-ad-slot="3707140914"></ins>
              <script>
              (adsbygoogle = window.adsbygoogle || []).push({});
              </script>
            </div>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->
      
      <hr>
      <div class="sitemap">
        <p>
          <%= link_to "使い方", usage_path, target: :_blank %> | 
          <%= link_to "注意事項", notice_path, target: :_blank %> | 
          <%= link_to "利用規約", agreement_path, target: :_blank %> |
          <%= link_to "よくある質問", q_and_a_path, target: :_blank %> |
          <%= link_to "問い合わせ", contact_path, target: :_blank %>
        </p>
      </div>
        
      <footer>
        <p>&copy; 2017 Satoshi Sanjo</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>